### ISSUE TITLE
Group Mode Case 1 (Bill Splitting)

### ISSUE THREAD

**Issue by crees-bree** [crees-bree/Barkada-Budget-Calculator#3]
- [x]  Create menu for case 1 to:
  - [x]  Add a new member (name, payment, bill)
    - [x]  Tagai siyag option na makaedit siya before i add ang member
  - [x]  Edit a member
  - [x]  Delete a member
  - [x]  Display each member details (name, bill, payment so far, change)
  - [x] Display total details (total bill, total change, total payment)

please ko edit sa to-do if naa pa bay ma add

**Comment by crees-bree** [comment]
naa koy gi add para display total details

**Comment by conxant0** [comment]
all done nani assuming no bugs

**Comment by crees-bree** [comment]
> all done nani assuming no bugs

gegege pls niya ko test if makatest ka tenksss
